# Generated by Django 6.1 on 2026-09-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_merge_0002_alter_student_course_0002_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
